from . import geo_utils
from . import res_partner
from . import res_groups
from . import mail_followers
from . import wmz_user_provision
from . import wmz_password_wizard
from . import pickup_point
from . import waste_container
from . import request_waste_service
from . import request_waste_service_workflow
from . import request_waste_service_actions
from . import request_waste_service_dashboard
from . import waste_disposal_site
from . import disposal_site_wizard_line
from . import disposal_site_wizard
from . import waste_worksheet
from . import service_request
from . import waste_type
from . import waste_details
from . import bin_type
from . import tank_volume
from . import container_type
from . import service_provider
from . import provider_wizard
from . import provider_wizard_line
from . import request_provider_wizard
from . import reject_service_request_wizard
from . import amend_service_request_widzard
from . import waste_service_request_extra_line
from . import product_product
from . import waste_request_assign_bin_wizard
from . import waste_request_bin_line
from . import res_company
from . import payment_provider
from . import res_user
from . import hr_department
from . import hr_employee
from . import hr_job
from . import fleet_vehicle
from . import fleet_vehicle_model_brand
from . import tank_tariff
from . import sales_order
from . import account_move
from . import ir_ui_menu
from . import ir_actions
from . import account_chart_template
from . import authorize_wizard
from . import finish_worksheet_wizard
from . import transport_rate
from . import sale_order_line
from . import account_move_line
from . import driver_signature




