{
    "name": "Waste Management",
    "version": "1.0",
    "author": "Lesiba",
    "depends": ['base','mail','sale', 'product','account','fleet','hr'],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/pickup_point_views.xml",
        "views/waste_container.xml",
        "views/request_waste_service.xml",
        "views/product_inherit.view.xml",
        "views/sale_order_view.xml",
        "views/hr_employee_view.xml",
        "views/fleet_vehicle_views.xml",
        "views/waste_disposal_site_views.xml",
        "views/waste_worksheet_view.xml",
        "popups/view_manifest_document_popup.xml",
        "popups/view_manifest_document_up_pop.xml",
        "popups/view_safety_certificate_popup.xml",
        "popups/view_safety_certificate_up_pop.xml",
        "popups/view_weighbridge_slip_popup.xml",
        "popups/view_weighbridge_slip_up_pop.xml",
        "wizard/driver_signature.xml",
        "views/waste_schedule_views.xml",
        # "views/waste_service_request_schedule_view.xml",
        "views/waste_delivery_views.xml",
        "views/waste_capture_views.xml",
        "views/waste_upload_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True
}
