{
    "name": "Sage Connector",
    "version": "17.0.1.3.8",
    "category": "Accounting",
    "summary": "Versioned Sage 50 Pastel Partner connector: jobs, mappings, incremental sync",
    "depends": ["base", "contacts", "product", "account", "mail", "pastel_connector"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/sage_connector_groups.xml",
        "security/ir.model.access.csv",
        "security/sage_connector_rules.xml",
        "data/ir_cron.xml",
        "views/sage_backend_views.xml",
        "views/sage_job_views.xml",
        "views/sage_sync_log_views.xml",
        "views/sage_mapping_views.xml",
        "wizard/sage_import_wizard_views.xml",
        "views/account_move_views.xml",
        "views/res_partner_views.xml",
        "views/product_views.xml",
        "views/sage_cleanup.xml",
        "views/sage_menu.xml",
        "views/res_config_settings_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "assets": {
        "web.assets_backend": [
            "sage_connector/static/src/css/sage_connector.css",
        ],
    },
}
