{
    "name": "Waste Management",
    "version": "1.0.164",
    "author": "Lesiba",
    "depends": [
        'base', 'mail', 'sale', 'product', 'account', 'payment', 'fleet', 'hr', 'stock',
        'portal',         'website', 'auth_signup', 'link_tracker',
        'vehicle_inspection', 'pastel_connector', 'sage_connector', 'company_smart_theme',
    ],
    "data": [
        "security/waste_groups.xml",
        "security/wmz_user_form_groups.xml",
        "security/waste_portal_groups.xml",
        "security/waste_portal_rules.xml",
        "security/waste_portal_access.xml",
        "security/ir.model.access.csv",
        "security/waste_rules.xml",
        "security/waste_popia_rules.xml",
        "security/payment_provider_restore.xml",

        "data/sequence.xml",
        "data/company_branding.xml",
        "data/customer_reference_sequence.xml",
        "data/customer_reference_sequence_fix.xml",
        "data/customer_reference_backfill.xml",
        "data/company_isolation_backfill.xml",
        "data/company_parent_backfill.xml",
        "data/popia_security_fix.xml",
        "data/service_provider_address_backfill.xml",
        "data/disposal_site_address_backfill.xml",
        "data/payment_provider_company_backfill.xml",
        "data/payment_provider_action_reset.xml",
        "data/portal_quotation_policy_backfill.xml",
        "data/tank_tariff_data.xml",
        "data/transport_tariff_data.xml",
        "data/mail_reject_manifest.xml",
        "data/mail_amend_manifest.xml",
        "data/mail_authorise_manifest.xml",
        "data/mai_assign_to_driver.xml",
        "data/mail_worksheet_completion.xml",
        "data/mail_invide_service_provider.xml",
        "data/mail_client_portal_worksheet_completion.xml",
        "data/mail_client_portal_request_completion.xml",
        # "report/waste_dashboard_report_action.xml",
        "report/portal_waste_report_pdf.xml",
        "report/report_waste_dashboard_pdf.xml",
        "views/report_manifest.xml",
        # "data/waste_config.xml",
        # "views/waste_dashboard_action.xml",


        # "views/auth_signup_templates.xml",
        "views/portal_waste_dashboard.xml",
        "views/portal_waste_report_html.xml",
        # "views/portal_validation.xml",
        "views/portal_validation_template.xml",
        "views/waste_portal_templates.xml",
        "views/website_landing.xml",
        "views/website_layout.xml",
        "views/web_login_templates.xml",
        "views/report_invoice_inherit.xml",
        "views/portal_sale_order.xml",
        "views/account_portal_templates.xml",
        "views/account_portal_invoice_list.xml",
        # "views/hide_cards_for_agent_group_temp.xml",

        "views/res_user_view.xml",
        "views/res_partner_view.xml",
        "views/contacts_action_views.xml",
        "views/service_request_user_view.xml",
        "views/wmz_password_wizard_views.xml",
        "views/governance_menus.xml",
        # "views/hide_sale_menu.xml",
        "views/pickup_point_views.xml",
        "views/waste_container.xml",
        "views/request_waste_service.xml",
        "views/waste_service_request_extra_line.xml",
        "views/waste_product_views.xml",
        "views/product_inherit.view.xml",
        "views/account_move_view.xml",
        "views/sale_order_view.xml",
        "views/sale_order_line_views.xml",
        "views/res_company_view.xml",
        "views/hr_employee_view.xml",
        "views/fleet_vehicle_module.xml",
        "views/fleet_vehicle_views.xml",
        "views/waste_disposal_site_views.xml",
        "views/waste_worksheet_view.xml",
        "views/service_request_view.xml",
        "views/waste_type_view.xml",
        "views/waste_details_view.xml",
        "views/bin_type_view.xml",
        "views/tank_volume_view.xml",
        "views/tank_tariff_views.xml",
        "views/wizard_views.xml",
        "views/service_provider_views.xml",
        "views/request_provider_wizard_views.xml",
        "views/disposal_site_wizard_views.xml",
        "views/reject_service_request_wizard_view.xml",
        "views/amend_service_request_widzard.xml",
        "views/waste_assign_bin_wizard_view.xml",
        "views/authorize_wizard_view.xml",
        "views/finish_worksheet_wizard.xml",
        "views/transport_rate_views.xml",
        # "views/waste_worksheet_assign_bin_wizard_view.xml",
        "views/remove_powered_by_odoo.xml",
        "views/container_type_view.xml",
        "popups/view_manifest_document_popup.xml",
        "popups/view_manifest_document_up_pop.xml",
        "popups/view_safety_certificate_popup.xml",
        "popups/view_safety_certificate_up_pop.xml",
        "popups/view_weighbridge_slip_popup.xml",
        "popups/view_weighbridge_slip_up_pop.xml",
        "views/waste_dashboard_menu.xml",

        "views/menu.xml",
        "views/payment_provider_menus.xml",
        "security/menu_security.xml",
    ],

    "assets": {
        "web._assets_primary_variables": [
            "waste_management_zakheni/static/src/scss/primary_variables.scss",
            "waste_management_zakheni/static/src/scss/website_color_variables.scss",
        ],
        "web.assets_frontend": [
            "/web/static/lib/chartjs/chart.umd.js",
            "waste_management_zakheni/static/src/css/branding.css",
            "waste_management_zakheni/static/src/css/odoo_theme.css",
            "waste_management_zakheni/static/src/css/portal_waste.css",
            "waste_management_zakheni/static/src/css/website_landing.css",
            "waste_management_zakheni/static/src/css/website_theme.css",
            "waste_management_zakheni/static/src/css/login.css",
            "waste_management_zakheni/static/src/js/website_theme.js",
            "waste_management_zakheni/static/src/js/login_password_toggle.js",
            "waste_management_zakheni/static/src/js/portal_home.js",
        ],

        "web.assets_backend": [
            "waste_management_zakheni/static/src/css/odoo_theme.css",
            # Chart.js (try both, Odoo builds differ)
            "web/static/lib/chartjs/chart.umd.js",
            "web/static/lib/Chart/Chart.js",

            "waste_management_zakheni/static/src/css/waste_worksheet_kanban.css",
            "waste_management_zakheni/static/src/css/waste_worksheet_form.css",
            "waste_management_zakheni/static/src/css/waste_manifest_form.css",
            "waste_management_zakheni/static/src/css/waste_manifest_kanban.css",
            "waste_management_zakheni/static/src/css/pickup_point_form.css",
            "waste_management_zakheni/static/src/css/waste_container_form.css",
            "waste_management_zakheni/static/src/css/service_provider_kanban.css",
            "waste_management_zakheni/static/src/css/disposal_site_kanban.css",
            "waste_management_zakheni/static/src/js/waste_worksheet_kanban.js",
            "waste_management_zakheni/static/src/js/worksheet_stopwatch.js",
            "waste_management_zakheni/static/src/xml/worksheet_stopwatch.xml",
            "waste_management_zakheni/static/src/dashboard/waste_dashboard.xml",
            "waste_management_zakheni/static/src/dashboard/waste_dashboard.css",
            "waste_management_zakheni/static/src/dashboard/waste_dashboard.js",

            "waste_management_zakheni/static/src/css/provider_map_widget.css",
            "waste_management_zakheni/static/src/js/provider_map_widget.js",
            "waste_management_zakheni/static/src/xml/provider_map_widget.xml",

        ],
    },

    "installable": True,
    "application": True,
    "post_init_hook": "post_init_seed_waste_config",

}
